### ISSUE TITLE
Change detection in frontend frameworks (React, Vue, Angular, etc.)

### ISSUE THREAD

**Issue by sonicoder86** [frontendmeetup/Proposals#5]
### This would be a great talk, because

Change detection is often hard to grasp when something not happens when it is supposed to and these are hard to debug if we dont understanding the underlying fundamentals of immutability.

### Abstract

Displayed data  within applications often change dynamically and this change needs to be reflected to the end user. What happens if the remote request completes, we update the stored data but on the UI nothing changes but it should? How does a framework detect if your data has changed? How can we detect different data points in Javascript?

In this talk I'll show with Javascript operators and features how can we detect if one set of data is different from another one and how do these are implemented in the biggest frameworks. The talk is targeted mainly on the existing Javascript features and not the quirks of each framework.

### Details
 
Estimated length in minutes: 20-30 mins

#### What language would you prefer to present this talk

- [x] english
- [ ] hungarian

#### Would your employer / company host the Meetup for this talk?

- [ ] yes!

**Comment by necccc** [comment]
Amazing topic! Thank you for submitting.
When do you think you could give this talk, end of October, or sometimes November maybe?

**Comment by sonicoder86** [comment]
November would be fine

**Comment by necccc** [comment]
Great! Let's aim for the end of November for now, thank you!

**Comment by sonicoder86** [comment]
i would postpone my talk to a later occasion starting from december, december january is fine

**Comment by necccc** [comment]
How about early December? It seems we'll have a host and other topics by then.

**Comment by sonicoder86** [comment]
Dec 8? seems fine

**Comment by necccc** [comment]
> Dec 8? seems fine

Great, thank you!
I'll add you and your talk to the agenda!
